translated_kw_dicts = {
    "restricted_kw": {
        "en": [
            "betting",
            "meet girls",
            "meet women",
            "meet ladies",
            "hot girls",
            "babes",
            "hot women",
            "single women",
            "single girls",
            "hooker",
            "prostitute"
            "snus",
            "snuff",
            "dating",
            "pharma",
            "pharmacy",
            "drug",
            "drugs",
            "lottery",
            "bet",
            "casino",
            "chips",
            "wager",
            "wagers",
            "teleservice",
            "escort",
            "telemarketing",
            "timeshare",
            "cigar",
            "cigarette",
            "ecigarette",
            "vape",
            "e-cigarette",
            "tobacco",
            "electronic cigarette",
            "smoke",
            "crypto",
            "bitcoin",
            "coin",
            "cryptocurrency",
            "forex",
            "intim",
            "sex",
            "sexy",
            "sexual",
            "porn",
            "pornography",
            "adolescent",
            "cocaine",
            "coke",
            "spice",
            "herbs",
            "marijuana",
            "weed",
            "rape",
            "fight",
            "beastality",
            "cum",
            "ass",
            "dick",
            "penis",
            "vagina",
            "tits",
            "breasts",
            "titty",
            "titties",
            "nipples",
            "blowjob",
            "gun",
            "guns",
            "weapon",
            "torture",
            "nude",
            "nudes",
            "incest",
            "shot",
            "kill",
            "killing",
            "killed",
            "stab",
            "stabing",
            "stabbed",
            "financial services",
            "salvia",
            "hash",
            "hashish",
            "vicodin",
            "oxycodone",
            "fuck",
            "percocet",
            "steroid",
            "anabolic",
            "vitamin",
            "vitamins",
            "peptides",
            "hgh",
            "tablet",
            "tablets",
            "kush",
            "spice",
            "pill",
            "pills",
            "subscription",
            "trial",
            "unlock",
            "uncrack",
            "crack",
            "meth",
            "desoxyn",
            "ald-52",
            "dolophine",
            "methadone",
            "eth-lad",
            "morphine",
            "al-lad",
            "narcan",
            "naloxone",
            "ketalar",
            "ibogaine",
            "5-meo dmt",
            "dexedrine",
            "xanax",
            "mephedrone",
            "4mmc",
            "dilaudid",
            "hydromorphone",
            "amphetamine",
            "methoxetamine",
            "mxe",
            "dmt",
            "psilocybin",
            "ritalin",
            "adderall",
            "subutex",
            "1p-eth-lad",
            "1p-lsd",
            "oxycontin",
            "ketamine",
            "fentanyl",
            "pcp",
            "phencyclidine",


        ],
        "lv": [
            "derības",
            "iepazīšanās",
            "farmācija",
            "aptieka",
            "narkotika",
            "narkotikas",
            "loterija",
            "derības",
            "kazino",
            "žetoni",
            "derības",
            "derības",
            "telemārketing",
            "eskorts",
            "telemārketings",
            "timeshare",
            "cigārs",
            "cigarete",
            "vape",
            "e-cigarete",
            "tabaka",
            "elektroniskā cigarete",
            "smēķēt",
            "kriptogrāfija",
            "bitcoin",
            "monēta",
            "kriptovalūta",
            "forex",
            "valūtas maiņa",
            "intīm",
            "sekss",
            "seksīga",
            "seksuāla",
            "pornogrāfija",
            "porno",
            "bērns",
            "pusaudzis",
            "kokaīns",
            "kokss",
            "uztura bagātinātājs",
            "homeopātija",
            "marihuāna",
            "zālīte",
            "izvarošana",
            "kaušanās",
            "zvērīgums",
            "sperma",
            "pēcpuse",
            "penis",
            "dzimumloceklis",
            "maksts",
            "ciči",
            "krūtis",
            "lielgabals",
            "ieroči",
            "ieročus",
            "spīdzināšana",
            "kaila",
            "incests",
            "nošaut",
            "nogalināt",
            "nogalināšana",
            "nogalināts",
            "durt",
            "duršana",
            "sadurts",
            "finanšu pakalpojumi",
            "salvija",
            "hash",
            "hašišs",
            "vikodīns",
            "oksikodons",
            "jāšanās",
            "percocet",
            "steroīdi",
            "anaboliķi",
            "vitamīns",
            "vitamīni",
            "peptīdi",
            "hgh",
            "tablete",
            "tabletes",
            "kush",
            "abonēt",
            "ikmēneša",
            "amfetamīns",
            "ritalīns",
            "adderall",
            "oksikontīns",
            "k2",
            "mdma",
            "ekstazī",
            "extasy",
            "molly",
            "halucinogēni",
            "lsd",
            "dxm",
            "dezoksēns",
            "ald-52",
            "dolofīns",
            "metadons",
            "eth-lad",
            "morfīns",
            "al-lads",
            "narcan",
            "naloksons",
            "ketalārs",
            "ibogaīns",
            "5-meo dmt",
            "dexedrīns",
            "ksanakss",
            "mefedrons",
            "4 mmc",
            "dilaudid",
            "hidromorfons",
            "amfetamīns",
            "metoksetamīns",
            "mxe",
            "dmt",
            "psilocibīns",
            "ritalīns",
            "adderall",
            "subutex",
            "1p-eth-lad",
            "ritalīns",
            "1p-lsd",
            "oksikontīns",
            "ketamīns",
            "fentanils",
            "pcp",
            "fenciklīds"
        ],
        "et": [
            "kohtuda tüdrukutega",
            "kohtuda naistega",
            "kohtuda daamid",
            "kuumad tüdrukud",
            "kuum babes",
            "kuumad naised",
            "vallalised naised",
            "vallalised tüdrukud",
            "ühe babes",
            "kihlvedu",
            "tutvumine",
            "farmaatsia",
            "apteek",
            "ravim",
            "ravimid",
            "loterii",
            "panused",
            "kasiino",
            "žetoonid",
            "panustamine",
            "panustamised",
            "eskort",
            "teleturundus",
            "osaajaline kasutamine",
            "sigar",
            "sigaret",
            "huuletubakas",
            "nuusktubakas",
            "esigaret",
            "vape",
            "e-sigaret",
            "tubakas",
            "elektrooniline sigaret",
            "suits",
            "krüpto",
            "bitcoin",
            "münt",
            "krüptoraha",
            "forex",
            "intiimne",
            "seks",
            "seksikas",
            "seksuaalne",
            "porno",
            "pornograafia",
            "väike",
            "nooruk",
            "kokaiin",
            "koks",
            "vürts",
            "maitsetaimed",
            "marihuaana",
            "umbrohi",
            "vägistama",
            "võitlus",
            "seksuaalvahekord loomaga",
            "keppima",
            "ejakuleerima",
            "perse",
            "munn",
            "peenis",
            "tupp",
            "tissid",
            "rinnad",
            "tiss",
            "tissid",
            "nibud",
            "suuseks",
            "püstol",
            "püstolid",
            "relvad",
            "piinamine",
            "alasti",
            "alasti inimesed",
            "verepilastus",
            "tulistama",
            "tapma",
            "tapmine",
            "tapetud",
            "torkama",
            "torkamine",
            "läbi torgatud",
            "finantsteenused",
            "salvei",
            "haš",
            "hašiš",
            "vikodiin",
            "oksükodoon",
            "perkotset",
            "streoid",
            "anaboolne",
            "vitamiin",
            "vitamiinid",
            "peptiidid",
            "hgh",
            "tablett",
            "tabletid",
            "kush",
            "pill",
            "pillid",
            "liitumine",
            "metamfetamiin",
            "ritaliin",
            "adderall",
            "oksükontiin",
            "k2",
            "mdma",
            "ecstasy",
            "extasy",
            "molly",
            "hallutsinogeenid",
            "lsd",
            "dxm",
            "homöopaatia",
            "desoxyn",
            "ald-52",
            "dolofiin",
            "metadoon",
            "eth-lad",
            "morfiin",
            "al-lad",
            "narcan",
            "naloksoon",
            "ketalar",
            "ibogain",
            "5-meo dmt",
            "deksedriin",
            "xanax",
            "mefedroon",
            "4mmc",
            "dilaudid",
            "hüdromorfoon",
            "amfetamiin",
            "metoksetamiin",
            "mxe",
            "dmt",
            "psilotsübiin",
            "ritaliin",
            "adderall",
            "subutex",
            "1p-eth-lad",
            "ritaliin",
            "1p-lsd",
            "oksükontiin",
            "ketamiin",
            "fentanüül",
            "pcp",
            "fentsüklidiin",
        ],
        "lt": [
            "susitikti su merginomis",
            "susitikti su moterimis",
            "susipažink su damomis",
            "karštos merginos",
            "karštos pupytės",
            "karštos moterys",
            "vienišos moterys",
            "vienišos merginos",
            "vienišos pupytės",
            "lažybos",
            "pasimatymai",
            "farmacija",
            "vaistinė",
            "vaistas",
            "vaistai",
            "loterija",
            "lažybos",
            "kazino",
            "traškučiai",
            "statymas",
            "statymai",
            "palydovas",
            "telerinkodara",
            "pakaitinio naudojimosi teisė",
            "cigaras",
            "cigaretė",
            "snusas",
            "snufas",
            "elektroninė cigaretė",
            "veipas",
            "elektroninė cigaretė",
            "tabakas",
            "elektroninė cigaretė",
            "dūmai",
            "kriptovaliuta",
            "bitkoinas",
            "moneta",
            "kriptovaliuta",
            "forex",
            "intymus",
            "seksas",
            "seksualus",
            "seksualinis",
            "pornografija",
            "pornografija",
            "smulkaus sudėjimo",
            "paauglys",
            "kokainas",
            "koksas",
            "prieskonis",
            "žolelės",
            "marihuana",
            "žolė",
            "išprievartavimas",
            "kova",
            "žvėriškumas",
            "dulkintis",
            "sperma",
            "šikna",
            "penis",
            "varpa",
            "makštis",
            "papai",
            "krūtys",
            "krūtis",
            "krūtys",
            "speneliai",
            "oralinis seksas",
            "ginklas",
            "ginklai",
            "ginklai",
            "kankinimas",
            "nuogumas",
            "nuogos nuotraukos",
            "kraujomaiša",
            "šauti",
            "nužudyti",
            "nužudymas",
            "nužudytas",
            "nudurti",
            "nudūrimas",
            "nudurtas",
            "finansinės paslaugos",
            "salvija",
            "hašas",
            "hašišas",
            "vikodinas",
            "oksikodonas",
            "perkocetas",
            "steroidas",
            "anabolikas",
            "vitaminas",
            "vitaminai",
            "peptidai",
            "apsinešęs",
            "tabletė",
            "tabletės",
            "kanapė",
            "tabletė",
            "tabletės",
            "prenumerata",
            "metamfetaminas",
            "ritalinas",
            "aderolis",
            "oksikontinas",
            "k2",
            "mdma",
            "ekstazė",
            "ekstazis",
            "molly",
            "haliucinogenai",
            "lsd",
            "dekstrometorfanas",
            "homeopatija",
            "desoksinas",
            "ald-52",
            "dolofinas",
            "metadonas",
            "eth-lad",
            "morfinas",
            "al-lad",
            "narcanas",
            "naloksonas",
            "ketalaras",
            "ibogainas",
            "5-meo dmt",
            "deksedrinas",
            "xanax",
            "mefedronas",
            "4mmc",
            "dilaudid",
            "hidromorfonas",
            "amfetaminas",
            "metoksetaminas",
            "mxe",
            "dmt",
            "psilocibinas",
            "ritalinas",
            "adderall",
            "subutex",
            "1p-eth-lad",
            "ritalinas",
            "1p-lsd",
            "oksikontinas",
            "ketaminas",
            "fentanilis",
            "pcp",
            "fenciklidinas"
        ],
        "ru": [
            "гемблинг",
            "сайт знакомств",
            "фармация",
            "аптека",
            "лекарства",
            "медикаменты",
            "лотерея",
            "ставки",
            "казино",
            "фишки",
            "эскорт",
            "телемаркетинг",
            "таймшер",
            "сигар",
            "сигарета",
            "снюс",
            "нюхательный табак",
            "электронная сигарета",
            "вейп",
            "табак",
            "курение",
            "крипто",
            "биткойн",
            "монеты",
            "криптовалюта",
            "форекс",
            "cekc",
            "сексуально",
            "сексуально",
            "порно",
            "порнография",
            "малышка",
            "подростки",
            "кокаин",
            "кокаин",
            "марихуана",
            "конопла",
            "изнасилование",
            "бой",
            "драка",
            "пипец",
            "камшот",
            "жопа",
            "хуй",
            "пенис",
            "вагина",
            "сиськи",
            "минет",
            "оружие",
            "оружие",
            "пытки",
            "инцест",
            "стрелять",
            "убить",
            "гаш",
            "гашиш",
            "викодин",
            "оксикон",
            "перкоцет",
            "стероиды",
            "анаболические",
            "витамин",
            "витамины",
            "пептиды",
            "грч",
            "таблетки",
            "куш",
            "таблетки",
            "таблетки",
            "подписка",
            "метамфетамин",
            "риталин",
            "оксикодон",
            "k2",
            "mdma",
            "экстази",
            "молли",
            "галлюциногенные",
            "лсд",
            "декстрометорфан",
            "гомеопатия",
            "азарт",
            "фармацевтические препараты",
            "телефонный маркетинг",
            "снафф",
            "э-сигарета",
            "трахать",
            "драка",
            "блять",
            "попка",
            "член",
            "пушка",
            "пушки",
            "пекодин",
            "первитин",
            "метилендиоксиамфетамин",
            "психодислептические",
            "dxm",
            "азартная игра",
            "наркотики",
            "ебать",
            "cyka",
            "пистолет",
            "дезоксиэфедрин",
            "дезоксин",
            "альд-52",
            "долофин",
            "eth-lad",
            "морфин",
            "аль-лад",
            "narcan",
            "налоксон",
            "кеталар",
            "кетамин",
            "ибогаин",
            "5-meo dmt",
            "декседрин",
            "xanax",
            "мефедрон",
            "4ммк",
            "дилаудид",
            "амфетамин",
            "метоксетамин",
            "mxe",
            "dmt",
            "псилоцибин",
            "риталин",
            "субутекс",
            "1p-eth-lad",
            "риталин",
            "1p-lsd",
            "оксиконтин",
            "фентанил",
            "pcp",
            "фенциклидин",
            "метадон",
            "гидроморфон"
        ],
        "fr": [
            "rencontrer des filles",
            "rencontrer des femmes",
            "rencontrer des dames",
            "filles sexy",
            "bombes sexy",
            "femmes sexy",
            "femmes célibataires",
            "filles célibataires",
            "bombes célibataires",
            "casino",
            "jetons",
            "pari",
            "paris",
            "escort",
            "télémarketing",
            "multipropriété",
            "cigare",
            "cigarette",
            "tabac à sucer",
            "tabac à priser",
            "cigarette électronique",
            "vapoteuse",
            "e-cigarette",
            "tabac",
            "cigarette électronique",
            "fumée",
            "crypto",
            "bitcoin",
            "monnaie",
            "crypto-monnaie",
            "forex",
            "intime",
            "sexe",
            "sexy",
            "sexuel",
            "porno",
            "pornographie",
            "petite",
            "adolescent",
            "cocaïne",
            "coke",
            "spice",
            "herbes",
            "marijuana",
            "cannabis",
            "viol",
            "combat",
            "bestialité",
            "baise",
            "sperme",
            "cul",
            "bite",
            "pénis",
            "vagin",
            "nichons",
            "seins",
            "téton",
            "tétons",
            "mamelons",
            "fellation",
            "fusil",
            "fusils",
            "armes",
            "torture",
            "nu",
            "nus",
            "inceste",
            "tire",
            "tue",
            "meurtre",
            "tué",
            "poignarder",
            "attaque au couteau",
            "poignardé",
            "services financiers",
            "salvia",
            "hasch",
            "haschisch",
            "vicodin",
            "oxycodone",
            "percocet",
            "stéroïdes",
            "anabolisant",
            "vitamine",
            "vitamines",
            "peptides",
            "hgh",
            "comprimé",
            "comprimés",
            "kush",
            "pilule",
            "pilules",
            "abonnement",
            "méthamphétamine",
            "ritaline",
            "adderall",
            "oxycontin",
            "k2",
            "mdma",
            "ecstasy",
            "extase",
            "molly",
            "hallucinogènes",
            "lsd",
            "dxm",
            "homéopathie",
            "desoxyn",
            "ald-52",
            "dolophine",
            "eth-lad",
            "morphine",
            "al-lad",
            "narcan",
            "naloxone",
            "ketalar",
            "ibogaine",
            "5-meo dmt",
            "dexedrine",
            "xanax",
            "méphédrone",
            "4mmc",
            "dilaudid",
            "amphétamine",
            "méthoxétamine",
            "mxe",
            "dmt",
            "psilocybine",
            "ritalin",
            "adderall",
            "subutex",
            "1p-eth-lad",
            "ritalin",
            "1p-lsd",
            "oxycontin",
            "kétamine",
            "fentanyl",
            "pcp",
            "phencyclidine",
            "hydromorphone",
            "méthadone"
        ]
    },
    "tc_kw": {
        "en": [
            "terms",
            "terms of use",
            "conditions",
            "cancellation"
        ],
        "lv": [
            "noteikumi",
            "nosacījumi",
            "atgriešana",
            "atgriezt"
        ],
        "et": [
            "terminid",
            "tingimused"
        ],
        "lt": [
            "sąlygos",
        ],
        "ru": [
            "условия",
            "pravila"
        ],
        "fr": [
            "termes",
            "conditions"
        ]
    },
    "refund_kw": {
        "en": [
            "refund",
            "return",
            "cancellation",
            "cancel"
        ],
        "lv": [
            "refund",
            "return",
            "cancellation",
            "atmaksa",
            "atgriešana",
            "atgriezt"
        ],
        "et": [
            "refund",
            "return",
            "cancellation",
            "tagasimakse",
            "tagastamine",
            "tühistamine"
        ],
        "lt": [
            "refund",
            "return",
            "cancellation",
            "pinigų grąžinimas",
            "grąžinimas",
            "atšaukimas"
        ],
        "ru": [
            "возмещения",
            "возврат",
            "отменить",
            "отмена"
        ],
        "fr": [
            "remboursement",
            "retour",
            "annulation",
            "refund",
            "return",
            "cancellation"
        ]
    },
    "delivery_kw": {
        "en": [
            "shipping",
            "delivery"
        ],
        "lv": [
            "shipping",
            "delivery",
            "piegāde",
            "piegade",
            "nosūtīšana"
        ],
        "et": [
            "shipping",
            "delivery",
            "tarne",
            "saatmine"
        ],
        "lt": [
            "shipping",
            "delivery",
            "pristatymas",
            "pristatymas"
        ],
        "ru": [
            "shipping",
            "delivery",
            "доставка",
            "отправка"
        ],
        "fr": [
            "shipping",
            "delivery",
            "livraison",
            "expédition"
        ]
    },
    "privacy_kw": {
        "en": [
            "privacy",
            "cookie",
            "gdpr",
            "confidentiality policy"
        ],
        "lv": [
            "privacy",
            "cookie",
            "gdpr",
            "privātuma",
            "privatuma",
            "konfidencialitātes politika"
        ],
        "et": [
            "cookie",
            "gdpr",
            "privacy",
            "privaatsus",
            "küpsised"
        ],
        "lt": [
            "cookie",
            "gdpr",
            "privacy",
            "privatumas",
            "slapukai"
        ],
        "ru": [
            "cookie",
            "gdpr",
            "конфиденциальности",
            "конфиденциальность",
            "политика"
        ],
        "fr": [
            "confidentialité",
            "gdpr",
            "rgpd",
            "cookies"
        ]
    },
    "pay_logos_kw": {
        "en": [
            "payment",
            "visa",
            "mastercard",
            "master",
            "maestro"
        ],
        "lv": [
            "payment",
            "visa",
            "mastercard",
            "card",
            "maestro",
        ],
        "et": [
            "payment",
            "visa",
            "mastercard",
            "card",
            "maestro",
        ],
        "lt": [
            "payment",
            "visa",
            "mastercard",
            "card",
            "maestro",
        ],
        "ru": [
            "payment",
            "visa",
            "mastercard",
            "card",
            "maestro",
        ],
        "fr": [
            "payment",
            "visa",
            "mastercard",
            "card",
            "maestro",
            "paiement"
        ]
    }
}
